project:
  type: website
  output-dir: docs

website:
  title: "My_Blog"
  navbar:
    right:
      - about.qmd
      - icon: person-info
        text: CV
        href: Resume2025.md
      - icon: person-info
        text: Cover Letter
        href: Cover Letter.md     
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

