project:
  type: website
  output-dir: docs

website:
  title: "Jesus Rodriguez"
  favicon: "images/jesus_rodriguez_picture.jpg"

  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Posts
        href: posts.qmd
      - text: Tidy Tuesday
        href: tidy_tuesday.qmd
      - text: Resume
        href: resume.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jesus-rodriguez-09ab12178
      - icon: github
        href: https://github.com/jesusrod44/portfolio
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

